### PR TITLE
added landing page components and connected waitliist form

### PR DESCRIPTION
**Pull request by noravgs**
I added the landing page components with animations and connected waitlist form there's another button hidden for whenever we connect the login/signup pages

Screen Shot 2024-08-28 at 3 17 03 PM

### CODE REVIEW

**Comment by Ewu694** [comment]
LGTM 👍

**Review by Ewu694 — APPROVED** [review]
Hopefully no merge conflicts

**Comment by lausan3** [comment]
> Hopefully no merge conflicts

There are no conflicts, but the branch has to be updated with main before merging. Please do this ASAP

**Comment by Ewu694** [comment]
> > Hopefully no merge conflicts
> 
> There are no conflicts, but the branch has to be updated with main before merging. Please do this ASAP

Passed all deployment rules, Merging this pull request 👍

**Pull request merged**
